language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build --build-arg GITHUB_CREDENTIALS_TOKEN=$GITHUB_CREDENTIALS_TOKEN web
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: NmsvoD4Cn8X5nfgB0f3MxrpTmEbH6Qx/sSvIYpnxm7w0q18DMThq2eEbdbVT2S1oNN52dY5kqCYxZKsolxsXEg3USNxZUZCOYS0aPLcx9715MmgM6CKjqeWZuyUsHtsQ70iYNtXBme5qy530lsEhqQDkVlZRu0vymUeHbkft5VrwVin0mGgGhsbtIEqqStVJ4w28uyvyZHzqKLpZnChijeE5Fxkvj7Fv4bkyFhC8hf/XhUFLjmBATC3OV1MXMHaAexmib/vR44FocN2FT4kbR3LnSaHEkLhj/66pZDkKLW5CkzIXZP/8U0dSHNglPzFMfo8R1yBm+mux5SDjQ4PJs7J/5MLdwzIrf8+hYZnJu7iNAhFONh52CDO3y3z582fy2otvL2NEDKT10cU1hXHlfIDzTAZ+x+EV22YVjXHhbg2H1Jp0oTOyJ0Dfdssyg6+wbBvs7DFeX+mT5jxsZcPtuF28HhvmtMR6XA6eWlUk6w7Yqg7aoiRNbcuipXAMMY3F4TLs2EAj7UXJGqhqENiHnPKwRlk+B3eI4WL1ec1/m3LMZZ7yrAy1CBr8njI2BYprIsUo5z2W7KLXee9UAefo5QCj6nJaHykH9TIFTfBk8KCDzGmHoO8PxL9x2LqTqPY9aPspO6/a3RyOLXcA0It2xSHDpLlEphDsEriJ3M6XxWQ=
  - secure: YAXMYSmrQYLWG/ylXIVJ/CJl9jyKf0rHWYpM55hrBWnsASyX8dICV3H0DbqEQVCuXbOKRupWpAFVgWTcuJhO/J3fEbs9oxf6f3wm60BovEdwwUmtwiH4wTm8c5D5hqB4R5ajvX0RFh1DyhRHDNA+QM0A1jmQDeuXe17vNoATR2TuqvzLZM6RYJBAWJP39vHCwJDt0nibznIQ8bjdL1y0AzFm93Bn9PxAwBiUXQ4EOqviEgtG05a+4EFfegSN4dNvZ0L2Y286pbJY4aPZE/vxIh+NuyvzRIBWpD5ncU24InCTloPX2FTPRS+/mi5NGbxlvndMXTsMqQY8bAgmCKOflx1XOkLjYwZUmkrB4GjyHwJIbhynkJ3IF5LZBn2ILo2XzMQH5yobCLsFJJhRi2N+bhSc9f1kmpN3/o1GbIZscT+USLutAAxiZdZ3qt7B1qoacLCRodIeZI2o6bh0+hAkda+0koCNhmD9zvO3nGU4JanghDMgFZF+z7MYnQspJf3LbtJGeqRP4MMfeDlNG4jgOZA+hamRPgJ76ShmW2h/9ss59JYxMDAzAnOZydICCfRSaEf69ZjBqGn/a7Bw/6zHhOnqZRauCuco+ALNlgVm7Gw0N8nJYMAgBLw1qe/pgyghM0dHrGVggkmX+Q4iZBkRGjZsg3eLe4kYV4Z50/OaYKU=
  - secure: gFREs37Y+0/6zwSj7ASk2R6Sp8Rgr+iB68NVkNBtEXpvSivf6DFP192JuahqRl4RJlvQlIiK9it6X7SKmPzXbiFLAxUQnPN8EvmA0L/yQFq5JJTng448/jP684vn0RjWevZiYxW+03JIbW4Ug1pFeS2X+V1OhdUCCk8fCUF0jPwC0SCQRK1gZlI9h4FKHvIWFqtNSMSMCiHlY8c2YJxdLVJZxCELJPHbW1OSUEA1Ro1dL7bdEpaclVqvVg19Ypyngtt93M0X4Mm3N2tfP09Bkx7n0yARx16tUNccliek9hIjo2HdAN/WpWjN3GMo1Cw+XmwhhvX7lbbSQ/FriuT6lcpxVi8D4M2CGPE8f+SzApNrrHvhn15pFcacFJErKLzbRAC7a7vCRdln1xPZ9B8NiIfZiPfcFIi26b5vwj2TyIiMNyj6DCuwt9WYMdDaPNsnT6kvPvOJ3JnfNRR6iGc0wou38c58CAARWbnCPuFY7fKY3g0jV3zds3wdL7h7oLPmjhXaZHja7n8Y6UwMBa+ZxA+FVPeCRcw+xVU50bHnve0LNPtUOLlO0uVgffv8abuwwrHSTAHqKEuTpSckyr31537WJj9McdKVtulK9se24jQcZyXREB9k40Rga7ysdSvnihlIf7R6+h5xqr6hHTWTTPE4wGdJkk+kUmbp4i1QAv4=
